AWSTemplateFormatVersion: '2010-09-09'
Description: 'Dynamodb table with lambda function'

Resources:
  Mytable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: "User ID"
          AttributeType: S
        - AttributeName: "Email"
          AttributeType: S
      KeySchema: 
        - AttributeName: "User ID"
          KeyType: HASH
        - AttributeName: "Email"
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
