---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'creating lambda function for s3 bucket code'

Resources:
  Lambda1:
    Type: "AWS::Lambda::Function"
    Properties: 
        Code:
            ZipFile: >
                def lambda_handler(event, context):
                return 'Hello from Aniket'
        Description: Test with Cloud Formation
        FunctionName: HelloWorldPyByCF
        Handler: index.lambda_handler
        ## enter your role arn here
        Role: arn:aws:iam::aws:policy/service-role/AWSLambdaRole
        Runtime: python2.7
